/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tela_Item_CadastroLote.java
 *
 * Created on 18/05/2012, 10:48:55
 */
package view;

import dados.ConectaBD;
import javax.swing.JOptionPane;
import javax.xml.bind.ParseConversionEvent;

/**
 *
 * @author Ricardo
 */
public class Tela_Item_CadastroLote extends javax.swing.JPanel {

    /** Creates new form Tela_Item_CadastroLote */
    public Tela_Item_CadastroLote() {
        initComponents();
        
        //preenche dados dos comboBoxs
        preencheDadosFormulario();
        
        
        //esconde o formulário interno de cadastro de fornecedor
        panelCadInternoFornecedor.setVisible(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoRegPatInicial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoRegPatFinal = new javax.swing.JTextField();
        campoDescricao = new javax.swing.JTextField();
        campoMarca = new javax.swing.JTextField();
        campoValor = new javax.swing.JTextField();
        botaoCadastrarItensLote = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        campoNumNF = new javax.swing.JTextField();
        campoNumEmpenho = new javax.swing.JTextField();
        campoFornecedor = new javax.swing.JTextField();
        ComboBoxCampus = new javax.swing.JComboBox();
        ComboBoxLocalizacao = new javax.swing.JComboBox();
        campoNumLicitacao = new javax.swing.JTextField();
        ComboBoxStatus = new javax.swing.JComboBox();
        ComboBoxCategoria = new javax.swing.JComboBox();
        campoDataEmissaoNF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ComboBoxResponsavel = new javax.swing.JComboBox();
        panelCadInternoFornecedor = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        botaoVerificarFornecedor = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 281));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Tela Cadastro em Lote Item");

        jLabel2.setText("Registro patrimonial");

        jLabel3.setText("Descrição:");

        jLabel4.setText("Marca:");

        jLabel5.setText("Valor:");

        campoRegPatInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRegPatInicialActionPerformed(evt);
            }
        });

        jLabel6.setText("De:");

        jLabel7.setText("Até:");

        botaoCadastrarItensLote.setText("Cadastrar Itens em Lote");
        botaoCadastrarItensLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarItensLoteActionPerformed(evt);
            }
        });

        jLabel8.setText("Número Nota Fiscal:");

        jLabel9.setText("Número Empenho:");

        jLabel10.setText("Fornecedor:");

        jLabel11.setText("Localização:");

        jLabel12.setText("Campus:");

        jLabel13.setText("Nº Licitação:");

        jLabel14.setText("Status:");

        jLabel15.setText("Categoria:");

        campoNumNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumNFActionPerformed(evt);
            }
        });

        ComboBoxCampus.setModel(new javax.swing.DefaultComboBoxModel());

        ComboBoxLocalizacao.setModel(new javax.swing.DefaultComboBoxModel());

        ComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel());

        ComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel());

        jLabel16.setText("Data Emissão NF:");

        jLabel17.setText("Responsável:");

        ComboBoxResponsavel.setModel(new javax.swing.DefaultComboBoxModel());

        panelCadInternoFornecedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Cadastro Fornecedor");

        jLabel19.setText("CNPJ:");

        jLabel20.setText("Nome:");

        jLabel21.setText("Telefone:");

        jLabel22.setText("Email:");

        jLabel23.setText("Representante:");

        jButton2.setText("Cadastrar Fornecedor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCadInternoFornecedorLayout = new javax.swing.GroupLayout(panelCadInternoFornecedor);
        panelCadInternoFornecedor.setLayout(panelCadInternoFornecedorLayout);
        panelCadInternoFornecedorLayout.setHorizontalGroup(
            panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadInternoFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadInternoFornecedorLayout.createSequentialGroup()
                        .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCadInternoFornecedorLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(68, 68, 68)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(panelCadInternoFornecedorLayout.createSequentialGroup()
                        .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addGap(21, 21, 21)
                        .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addGap(220, 220, 220))
                    .addGroup(panelCadInternoFornecedorLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(315, Short.MAX_VALUE))))
        );
        panelCadInternoFornecedorLayout.setVerticalGroup(
            panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadInternoFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(11, 11, 11)
                .addGroup(panelCadInternoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        botaoVerificarFornecedor.setText("Verificar Fornecedor");
        botaoVerificarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVerificarFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ComboBoxCampus, 0, 216, Short.MAX_VALUE)
                                    .addComponent(ComboBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBoxStatus, 0, 216, Short.MAX_VALUE)
                                    .addComponent(ComboBoxResponsavel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(botaoCadastrarItensLote, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoRegPatInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoRegPatFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNumEmpenho, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNumLicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoDataEmissaoNF)
                                    .addComponent(campoNumNF, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))))))
                .addGap(19, 19, 19)
                .addComponent(botaoVerificarFornecedor)
                .addGap(18, 18, 18)
                .addComponent(panelCadInternoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoRegPatInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRegPatFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelCadInternoFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoDataEmissaoNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(campoNumEmpenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botaoVerificarFornecedor)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(campoNumLicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ComboBoxLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(ComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ComboBoxResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarItensLote)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void campoRegPatInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRegPatInicialActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_campoRegPatInicialActionPerformed

private void botaoCadastrarItensLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarItensLoteActionPerformed
    
         ConectaBD conectaDB = new ConectaBD();
         
         int registroInicial = Integer.parseInt(campoRegPatInicial.getText().toString());
         int registroFinal = Integer.parseInt(campoRegPatFinal.getText().toString());
         
         for(int i = registroInicial; i <= registroFinal; i++){
         
         
             conectaDB.insert("item", "registro_patrimonial, descricao, marca, valor, numNF, dataNF, empenho, "
                     
                     + "fornecedor_cnpj, licitacao, localizacao_idlocalizacao, campus, status_idstatus, categoria_idcategoria, responsavel_siape",
                     
                     
                     
                     "'"+ i +"','"+campoDescricao.getText().toString()+"'"
                     
                     + ",'"+ campoMarca.getText().toString()+"',"+ campoValor.getText().toString()+""
                     
                     + ",'"+ Integer.parseInt( campoNumNF.getText().toString() ) +"',"+ Integer.parseInt( campoDataEmissaoNF.getText().toString() )+""
                     
                     + ",'"+ Integer.parseInt( campoNumEmpenho.getText().toString() ) +"',"+ Integer.parseInt( campoFornecedor.getText().toString() )+""
                     
                     //+ ","+ Integer.parseInt( campoNumLicitacao.getText().toString() )+""
                     + ","+ Integer.parseInt( campoNumLicitacao.getText().toString() ) +","+ obtemIndexSelecLocalizacao() +""
                     
                     + ","+ obtemIndexSelecCampus() +","+ obtemIndexSelecStatus() +","+ obtemIndexSelecCategoria() +""
                     
                     + ","+ obtemIndexSelecResponsavel() +""
                     
                     + "");
         }
         
         //fecha a conexão com o banco
         //conectaDB.closedConnection();
         
         //limpa os campos
         campoDescricao.setText("");
         campoMarca.setText("");
         campoValor.setText("");
         campoRegPatInicial.setText("");
         campoRegPatFinal.setText("");
         
         //obtemIndexSelecLocalizacao();
         //obtemIndexSelecCampus();
         //obtemIndexSelecStatus();
         //obtemIndexSelecCategoria();
         
         
         //System.out.println( "CAMPUS: "+ComboBoxCampus.getSelectedIndex() );
         //System.out.println( "CATEGORIA: "+ComboBoxCategoria.getSelectedIndex() );
         //System.out.println( "LOCALIZAÇÃO: "+ComboBoxLocalizacao.getSelectedIndex() );
         //System.out.println( "STATUS: "+ComboBoxStatus.getSelectedIndex() );         
         
         
         JOptionPane.showMessageDialog(null, "Cadastro realizado com Sucesso!");
    
}//GEN-LAST:event_botaoCadastrarItensLoteActionPerformed


private void campoNumNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumNFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_campoNumNFActionPerformed

private void botaoVerificarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerificarFornecedorActionPerformed

    
    panelCadInternoFornecedor.setVisible(true);
    
    
}//GEN-LAST:event_botaoVerificarFornecedorActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxCampus;
    private javax.swing.JComboBox ComboBoxCategoria;
    private javax.swing.JComboBox ComboBoxLocalizacao;
    private javax.swing.JComboBox ComboBoxResponsavel;
    private javax.swing.JComboBox ComboBoxStatus;
    private javax.swing.JButton botaoCadastrarItensLote;
    private javax.swing.JButton botaoVerificarFornecedor;
    private javax.swing.JTextField campoDataEmissaoNF;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoFornecedor;
    private javax.swing.JTextField campoMarca;
    private javax.swing.JTextField campoNumEmpenho;
    private javax.swing.JTextField campoNumLicitacao;
    private javax.swing.JTextField campoNumNF;
    private javax.swing.JTextField campoRegPatFinal;
    private javax.swing.JTextField campoRegPatInicial;
    private javax.swing.JTextField campoValor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    public javax.swing.JPanel panelCadInternoFornecedor;
    // End of variables declaration//GEN-END:variables



    public void preencheComboBoxLocalizacao(){
        
        ComboBoxLocalizacao.removeAllItems();
       try{
           ConectaBD conectaDB = new ConectaBD();

           conectaDB.select("*", "localizacao"," order by idlocalizacao asc");

           ComboBoxLocalizacao.addItem("<<            Selecione            >>");

           while( conectaDB.getResultSet().next() ){

                ComboBoxLocalizacao.addItem( conectaDB.resultSet.getString("idlocalizacao").toString()+" | Prédio: "+conectaDB.resultSet.getString("predio").toString()+" | Sala: "+conectaDB.resultSet.getString("sala").toString());
           } 
                    
        }catch(Exception erro){
        
            JOptionPane.showMessageDialog(null, "Erro ao listar dados, erro: "+erro);
            
        }
    }

    public void preencheComboBoxCampus(){
        
       ComboBoxCampus.removeAllItems();
       try{
           ConectaBD conectaDB = new ConectaBD();

           conectaDB.select("*", "campus"," order by id asc");

           
           ComboBoxCampus.addItem("<<            Selecione            >>");

           while( conectaDB.getResultSet().next() ){

                ComboBoxCampus.addItem( conectaDB.resultSet.getString("id").toString()+" | Campus: "+conectaDB.resultSet.getString("campus").toString());
           } 
                    
        }catch(Exception erro){
        
            JOptionPane.showMessageDialog(null, "Erro ao listar dados, erro: "+erro);
            
        }
    }
    
    
     public void preencheComboBoxStatus(){
         
       ComboBoxStatus.removeAllItems();  
       try{
           ConectaBD conectaDB = new ConectaBD();

           conectaDB.select("*", "status"," order by idstatus asc");

           

           
           ComboBoxStatus.addItem("<<            Selecione            >>");

           while( conectaDB.getResultSet().next() ){

                ComboBoxStatus.addItem( conectaDB.resultSet.getString("idstatus").toString()+" | Status: "+conectaDB.resultSet.getString("status").toString());
           } 
                    
        }catch(Exception erro){
        
            JOptionPane.showMessageDialog(null, "Erro ao listar dados, erro: "+erro);
            
        }
    }
    
    public void preencheComboBoxCategoria(){

       ComboBoxCategoria.removeAllItems();
       try{
           ConectaBD conectaDB = new ConectaBD();

           conectaDB.select("*", "categoria"," order by idcategoria asc");

           

           
           ComboBoxCategoria.addItem("<<            Selecione            >>");

           while( conectaDB.getResultSet().next() ){

                ComboBoxCategoria.addItem( conectaDB.resultSet.getString("idcategoria").toString()+" | Categoria: "+conectaDB.resultSet.getString("nome").toString());
           } 
                    
        }catch(Exception erro){
        
            JOptionPane.showMessageDialog(null, "Erro ao listar dados, erro: "+erro);
            
        }
    } 
    
    
    
    public void preencheComboBoxResponsavel(){

       ComboBoxResponsavel.removeAllItems();
       try{
           ConectaBD conectaDB = new ConectaBD();

           conectaDB.select("*", "responsavel"," order by siape asc");

           

           
           ComboBoxResponsavel.addItem("<<            Selecione            >>");

           while( conectaDB.getResultSet().next() ){

                ComboBoxResponsavel.addItem( conectaDB.resultSet.getString("siape").toString()+" | Nome: "+conectaDB.resultSet.getString("nome").toString());
           } 
                    
        }catch(Exception erro){
        
            JOptionPane.showMessageDialog(null, "Erro ao listar dados, erro: "+erro);
            
        }
    } 
     
    public void preencheDadosFormulario(){
    
        
        preencheComboBoxLocalizacao();
        preencheComboBoxCampus();
        preencheComboBoxStatus();
        preencheComboBoxCategoria();
        preencheComboBoxResponsavel();
    
    }
    
    public int obtemIndexSelecLocalizacao(){
       
      
       try{
           ConectaBD conectaDB = new ConectaBD();
           conectaDB.select("*", "localizacao"," order by idlocalizacao asc");
           
           int idBD = 0;
           int cont = 1; 
           while( conectaDB.getResultSet().next() ){

               if( cont == ComboBoxLocalizacao.getSelectedIndex()  ){
               
                   idBD = conectaDB.resultSet.getInt("idlocalizacao");
               }
               cont++;
           } 
           
           //System.out.println( "LOCALIZAÇÃO DB: "+idBD);
           return idBD;
           
        }catch(Exception erro){
        
            JOptionPane.showMessageDialog(null, "Erro ao obter dados, erro: "+erro);
        }    
        
       return 0;
    }
    
    public int obtemIndexSelecCampus(){
        
       try{
           ConectaBD conectaDB = new ConectaBD();
           conectaDB.select("*", "campus"," order by id asc");

           int idBD = 0;
           int cont = 1; 
           while( conectaDB.getResultSet().next() ){

               if( cont == ComboBoxCampus.getSelectedIndex()  ){
               
                   idBD = conectaDB.resultSet.getInt("id");
               }
               cont++;
           }
           
           //System.out.println( "CAMPUS DB: "+idBD);
           return idBD;
           
           
           
        }catch(Exception erro){
        
            JOptionPane.showMessageDialog(null, "Erro ao obter dados, erro: "+erro);
        }    
       
        return 0;
    }
    
    
    public int obtemIndexSelecStatus(){
        
       try{
           ConectaBD conectaDB = new ConectaBD();
           conectaDB.select("*", "status"," order by idstatus asc");

           int idBD = 0;
           int cont = 1; 
           while( conectaDB.getResultSet().next() ){

               if( cont == ComboBoxStatus.getSelectedIndex()  ){
               
                   idBD = conectaDB.resultSet.getInt("idstatus");
               }
               cont++;
           }
           
           //System.out.println( "STATUS DB: "+idBD);
           return idBD;
           
           
           
        }catch(Exception erro){
        
            JOptionPane.showMessageDialog(null, "Erro ao obter dados, erro: "+erro);
        }    
       
        return 0;
    }

    public int obtemIndexSelecCategoria(){
        
       try{
           ConectaBD conectaDB = new ConectaBD();
           conectaDB.select("*", "categoria"," order by idcategoria asc");

           int idBD = 0;
           int cont = 1; 
           while( conectaDB.getResultSet().next() ){

               if( cont == ComboBoxCategoria.getSelectedIndex()  ){
               
                   idBD = conectaDB.resultSet.getInt("idcategoria");
               }
               cont++;
           }
           
           //System.out.println( "CATEGORIA DB: "+idBD);
           return idBD;
           
           
           
        }catch(Exception erro){
        
            JOptionPane.showMessageDialog(null, "Erro ao obter dados, erro: "+erro);
        }    
       
        return 0;
    }

    
    public int obtemIndexSelecResponsavel(){
        
       try{
           ConectaBD conectaDB = new ConectaBD();
           conectaDB.select("*", "responsavel"," order by siape asc");

           int idBD = 0;
           int cont = 1; 
           while( conectaDB.getResultSet().next() ){

               if( cont == ComboBoxResponsavel.getSelectedIndex()  ){
               
                   idBD = conectaDB.resultSet.getInt("siape");
               }
               cont++;
           }
           
           //System.out.println( "CATEGORIA DB: "+idBD);
           return idBD;
           
           
           
        }catch(Exception erro){
        
            JOptionPane.showMessageDialog(null, "Erro ao obter dados, erro: "+erro);
        }    
       
        return 0;
    }
    
    
    
    
    
    
    
    
    
}
